### ISSUE TITLE
share和push依赖冲突

### ISSUE THREAD

**Issue by yan-jie** [songxiaoliang/react-native-share#42]
```
java.lang.NoSuchFieldError: No static field umDebugLog of type Lcom/umeng/commonsdk/debug/UMLog; in class Lcom/umeng/commonsdk/UMConfigure; or its superclasses (declaration of 'com.umeng.commonsdk.UMConfigure' appears in /data/app/com.dcash.wallet-uObBtBJzJc000yPtn6WN6g==/base.apk!classes4.dex)
        at com.umeng.message.common.UmengMessageDeviceConfig.getDeviceId(UmengMessageDeviceConfig.java:263)
        at com.umeng.message.common.b.a(Header.java:318)
        at com.umeng.message.common.b.b(Header.java:365)
        at com.umeng.message.UTrack.e(UTrack.java:663)
        at com.umeng.message.UTrack.<init>(UTrack.java:84)
        at com.umeng.message.UTrack.getInstance(UTrack.java:89)
        at com.umeng.message.PushAgent.addAlias(PushAgent.java:361)
        at com.dcash.wallet.service.push.PushManager.registerPush(PushManager.java:102)
        at com.dcash.wallet.service.push.PushManager.<init>(PushManager.java:50)
        at com.dcash.wallet.service.push.PushManager.inst(PushManager.java:61)
        at com.dcash.wallet.MainApplication.initPushSdk(MainApplication.java:85)
        at com.dcash.wallet.MainApplication.onCreate(MainApplication.java:66)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1123)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6636)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```
以上是启动crash日志

gradle依赖为

```
implementation 'com.umeng.sdk:common:1.5.1'
implementation 'com.umeng.sdk:push:4.2.0'
implementation 'com.umeng.sdk:share-core:6.9.2'
```
调试发现，push依赖的common包需为1.5.3版本，share-core依赖的common需为1.5.1版本

主要问题出在common包的 UMConfigure.umDebugLog 类型不一样

**Comment by songxiaoliang** [comment]
@yan-jie 可以以官方的最新依赖包为准。统一一下即可。
