### ISSUE TITLE
安卓下测试运行，apk刚打开，就闪退了

### ISSUE THREAD

**Issue by githuchunyu** [songxiaoliang/react-native-share#9]
react-native run-android，编译完了注入的时候，手机上apk打开秒退，之后手动打开都是闪退

**Comment by githuchunyu** [comment]
备注掉UMShareAPI.get(this)就不会闪退

**Comment by songxiaoliang** [comment]
@githuchunyu Android什么版本

**Comment by githuchunyu** [comment]
安卓5.1.1

**Comment by githuchunyu** [comment]
@songxiaoliang 安卓5.1.1

**Comment by songxiaoliang** [comment]
@githuchunyu 版本没问题，可否发下错误日志？

**Comment by githuchunyu** [comment]
@songxiaoliang 我这边没有显示错误，只是有闪退这个现象，不过我说一下我操作的一些细节。
1，我只需要新浪微博分享，所以在包名下，我只添加了modules和weibo，mainfest文件里也提出了其他分享模块；
2，由于我使用了react-native-wechat插件，因为要用到微信支付，然后编译出错，查询得知是包文件冲突，所以我删掉了此插件libs里的wechat-sdk包
然后编译就没有问题了，只是执行到最后手机打开测试apk之后闪退，如果备注到那行，在执行share方法的时候也会闪退。

**Comment by songxiaoliang** [comment]
@githuchunyu 这个还需要你自己排除问题。

**Comment by bestsamcn** [comment]
遇到同样的问题，我用adb logcat打印了日志，请问你解决了没，解决记得回下我啊

```
V/fb-UnpackingSoSource(12908): starting syncer worker
V/fb-UnpackingSoSource(12908): releasing dso store lock for /data/data/com.reactnativeblog/lib-main (from syncer thread)
V/fb-UnpackingSoSource(12908): not releasing dso store lock for /data/data/com.reactnativeblog/lib-main (syncer thread started)
W/ActivityManager(  746): getRunningAppProcesses: caller 10147 does not hold REAL_GET_TASKS; limiting output
W/ActivityManager(  746): getRunningAppProcesses: caller 10147 does not hold REAL_GET_TASKS; limiting output
E/umengsocial(12908): ----sdkversion:6.8.3---
E/umengsocial(12908):  濡搿쳠浠讳??쀿?氿찿?规坊?�唬?怿?Config.DEBUG = true
E/umengsocial(12908): ??耿?璇ꀿ렀棰밿糭?瀿?缃?렀棰밿?璇峰飙?栿듞妗ｏ?https://at.umeng.com/0fqeCy?cid=476
E/AndroidRuntime(12908): FATAL EXCEPTION: pool-3-thread-1
E/AndroidRuntime(12908): Process: com.reactnativeblog, PID: 12908
E/AndroidRuntime(12908): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/umeng/commonsdk/stateless/UMSLEnvelopeBuild;
E/AndroidRuntime(12908): 	at com.umeng.socialize.net.dplus.UMWorkDispatch.sendEvent(UMWorkDispatch.java:33)
E/AndroidRuntime(12908): 	at com.umeng.socialize.net.dplus.DplusApi$1.run(DplusApi.java:46)
E/AndroidRuntime(12908): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(12908): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(12908): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(12908): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.umeng.commonsdk.stateless.UMSLEnvelopeBuild" on path: DexPathList[[zip file "/data/app/com.reactnativeblog-1/base.apk"],nativeLibraryDirectories=[/data/app/com.reactnativeblog-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(12908): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(12908): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(12908): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(12908): 	... 5 more
E/AndroidRuntime(12908): 	Suppressed: java.lang.ClassNotFoundException: com.umeng.commonsdk.stateless.UMSLEnvelopeBuild
E/AndroidRuntime(12908): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(12908): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(12908): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(12908): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(12908): 		... 6 more
E/AndroidRuntime(12908): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
I/Process (12908): Sending signal. PID: 12908 SIG: 9
W/ActivityManager(  746):   Force finishing activity 1 com.reactnativeblog/.MainActivity
W/ActivityManager(  746): Exception thrown during pause
W/ActivityManager(  746): android.os.DeadObjectException
W/ActivityManager(  746): 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager(  746): 	at android.os.BinderProxy.transact(Binder.java:496)
W/ActivityManager(  746): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
W/ActivityManager(  746): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
W/ActivityManager(  746): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2726)
W/ActivityManager(  746): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2583)
W/ActivityManager(  746): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2497)
W/ActivityManager(  746): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11505)
W/ActivityManager(  746): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11402)
W/ActivityManager(  746): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12086)
W/ActivityManager(  746): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11597)
W/ActivityManager(  746): 	at com.android.server.am.ActivityManagerService.handleApplicationCrash(ActivityManagerService.java:11579)
W/ActivityManager(  746): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1406)
W/ActivityManager(  746): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2208)
W/ActivityManager(  746): 	at android.os.Binder.execTransact(Binder.java:446)
E/lowmemorykiller(  174): Error writing /proc/12908/oom_score_adj; errno=22
I/ActivityManager(  746): Process com.reactnativeblog (pid 12908) has died
```
